#!/usr/bin/python3
def raise_exception():
    w = 4 + 'u'
